# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: harbor-satellite

git:
  ignore_tags:
    - "*-ground-control"
builds:
  - main: "./main.go"
    binary: "{{ .Env.APP_NAME }}"
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s -X github.com/Mehul-Kumar-27/harbor-satellite/internal/version.GitCommit={{.FullCommit}}
    goos:
      - linux
      - darwin
    goarch:
      - "amd64"
      - "arm64"
      - "ppc64le"
      - "s390x"
      - "386"
      - "loong64"
      - "mips64"
      - "mips64le"
      - "mips"
      - "mipsle"
      - "riscv64"
    ignore:
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: loong64
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mips64le
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: riscv64
    mod_timestamp: "{{ .CommitTimestamp }}"

release:
  name_template: "{{ .Tag }}"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .Env.APP_NAME }}
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
