# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: ground-control

git:
  ignore_tags:
    - "*-satellite"

builds:
  - main: "./main.go"
    binary: "{{ .Env.APP_NAME }}"
    dir: "./ground-control"
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s -X github.com/container-registry/harbor-satellite/internal/version.GitCommit={{.FullCommit}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
      - "386"
      - loong64
      - mips64
      - mips64le
      - mips
      - mipsle
      - riscv64
    ignore:
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: loong64
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mips64le
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: riscv64
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - "{{ .ProjectName }}-{{ .ShortCommit}}"

nfpms:
  -
    homepage: https://github.com/container-registry/harbor-satellite
    maintainer: Harbor Community
    description: |-
      Ground Control is a tool to manage Harbor Satellite instances.
    formats:
      - rpm
      - deb
      - apk
      - archlinux

sboms:
  - artifacts: archive

release:
  name_template: "{{ .Tag }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Env.APP_NAME }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "merge conflict"
  groups:
    - title: "Dependency updates"
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: "Other work"
      order: 9999
