ContainerdEndpoint = ""
ContainerdRootDir = ""
RootDir = ""
StateDir = ""
cdi_spec_dirs = []
device_ownership_from_security_context = false
disable_apparmor = false
disable_cgroup = false
disable_hugetlb_controller = false
disable_proc_mount = false
disable_tcp_service = false
drain_exec_sync_io_timeout = ""
enable_cdi = false
enable_selinux = false
enable_tls_streaming = false
enable_unprivileged_icmp = false
enable_unprivileged_ports = false
ignore_deprecation_warnings = []
ignore_image_defined_volumes = false
image_pull_progress_timeout = ""
image_pull_with_sync_fs = false
max_concurrent_downloads = 0
max_container_log_line_size = 0
netns_mounts_under_state_dir = false
restrict_oom_score_adj = false
sandbox_image = ""
selinux_category_range = 0
stats_collect_period = 0
stream_idle_timeout = ""
stream_server_address = ""
stream_server_port = ""
systemd_cgroup = false
tolerate_missing_hugetlb_controller = false
unset_seccomp_profile = ""

[cni]
  bin_dir = ""
  conf_dir = ""
  conf_template = ""
  ip_pref = ""
  max_conf_num = 0
  setup_serially = false

[containerd]
  default_runtime_name = ""
  disable_snapshot_annotations = false
  discard_unpacked_layers = false
  ignore_blockio_not_enabled_errors = false
  ignore_rdt_not_enabled_errors = false
  no_pivot = false
  snapshotter = ""

  [containerd.default_runtime]
    base_runtime_spec = ""
    cni_conf_dir = ""
    cni_max_conf_num = 0
    container_annotations = []
    pod_annotations = []
    privileged_without_host_devices = false
    privileged_without_host_devices_all_devices_allowed = false
    runtime_engine = ""
    runtime_path = ""
    runtime_root = ""
    runtime_type = ""
    sandbox_mode = ""
    snapshotter = ""

    [containerd.default_runtime.options]

  [containerd.runtimes]

  [containerd.untrusted_workload_runtime]
    base_runtime_spec = ""
    cni_conf_dir = ""
    cni_max_conf_num = 0
    container_annotations = []
    pod_annotations = []
    privileged_without_host_devices = false
    privileged_without_host_devices_all_devices_allowed = false
    runtime_engine = ""
    runtime_path = ""
    runtime_root = ""
    runtime_type = ""
    sandbox_mode = ""
    snapshotter = ""

    [containerd.untrusted_workload_runtime.options]

[image_decryption]
  key_model = ""

[registry]
  config_path = "/etc/containerd/certs.d"

  [registry.auths]

  [registry.configs]

    [registry.configs."127.0.0.1"]

      [registry.configs."127.0.0.1".tls]
        ca_file = ""
        cert_file = ""
        insecure_skip_verify = true
        key_file = ""

  [registry.headers]

  [registry.mirrors]

    [registry.mirrors."127.0.0.1"]
      endpoint = ["127.0.0.1:8585"]

[x509_key_pair_streaming]
  tls_cert_file = ""
  tls_key_file = ""
