name: Publish Image

on:
  workflow_dispatch:
    inputs:
      use-registry-password:
        description: 'Use registry password to sign the image'
        default: true
        type: boolean
      actions-id-token-request-url:
        description: 'Actions ID token request URL'
        default: ''
        type: string

env:
  # Non-secret environment variables
  REGISTRY: ${{ secrets.REGISTRY }}
  GROUND_CONTROL: ground-control
  SATELLITE: satellite
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
  ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
  USE_REGISTRY_PASSWORD: ${{ github.event.inputs.use-registry-password }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Image for Ground Control
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          args: "publish-image-and-sign \
            --registry='${{ env.REGISTRY }}' \
            --registry-username='${{ env.REGISTRY_USERNAME }}' \
            --registry-password=env:REGISTRY_PASSWORD \
            --github-token=env:GITHUB_TOKEN \
            --component='${{ env.GROUND_CONTROL }}' \
            --actions-id-token-request-url='${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}' \
            --actions-id-token-request-token=env:ACTIONS_ID_TOKEN_REQUEST_TOKEN \
            --use-registry-password=${{ env.USE_REGISTRY_PASSWORD }}"

      - name: Publish Image for Satellite
        uses: dagger/dagger-for-github@v7
        with:
          verb: call
          args: "publish-image-and-sign \
            --registry='${{ env.REGISTRY }}' \
            --registry-username='${{ env.REGISTRY_USERNAME }}' \
            --registry-password=env:REGISTRY_PASSWORD \
            --github-token=env:GITHUB_TOKEN \
            --component='${{ env.SATELLITE }}' \
            --actions-id-token-request-url='${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}' \
            --actions-id-token-request-token=env:ACTIONS_ID_TOKEN_REQUEST_TOKEN \
            --use-registry-password=${{ env.USE_REGISTRY_PASSWORD }}"
